<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>API测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">API测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> xj</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-09-30 15:18:33</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:07.825369</p>
<p class='attribute'><strong>测试结果 : </strong> 共 7，错误 7，通过率= 0.00%</p>

<p class='description'>登录与注册的get请求用例</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 7 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>api_project_3.test_data.register_test_case.HttpTest</td>
    <td class="text-center">7</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',7)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_1_正常注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: 开始执行用例啦
正在发起get请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register?mobilephone=13999100087&amp;pwd=123456 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C645BD438&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_2_输入已经注册的手机号</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: 开始执行用例啦
正在发起get请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register?mobilephone=13888888886&amp;pwd=123456 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C645BDC18&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_3_手机号码为空注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: 开始执行用例啦
正在发起post请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C64595CC0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_4_密码为空进行注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: 开始执行用例啦
正在发起post请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C64595470&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_5_输入小于六位的手机号注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: 开始执行用例啦
正在发起get请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register?mobilephone=13577&amp;pwd=123456 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C64467A20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_6_输入大于11位的手机号进行注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: 开始执行用例啦
正在发起get请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register?mobilephone=135778876763&amp;pwd=123456 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C64467390&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_2_7_输入带有特殊字符的手机号注册</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: 开始执行用例啦
正在发起post请求
错误是HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000026C64595860&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
用例执行完毕啦
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\lib\site-packages\ddt.py", line 153, in wrapper
    return func(self, *args, **kwargs)
  File "E:\learning_python_class\api_project_3\test_data\register_test_case.py", line 34, in test_2
    resp_t=HttpRequest(url,method,eval(param)).http_request(cookie)
  File "E:\learning_python_class\api_project_3\common\http_request.py", line 33, in http_request
    return resp #返回结果
UnboundLocalError: local variable 'resp' referenced before assignment


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>7</td>
    <td>0</td>
    <td>0</td>
    <td>7</td>
    <td>通过率：0.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
